CREATE TABLE `negosyante_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`firstName` varchar(255),
	`middleName` varchar(255),
	`lastName` varchar(255),
	`suffix` varchar(50),
	`dateOfBirth` varchar(20),
	`gender` enum('male','female'),
	`civilStatus` enum('single','married','widowed','legally_separated'),
	`citizenship` varchar(100) DEFAULT 'Filipino',
	`placeOfBirth` varchar(255),
	`mothersName` varchar(255),
	`fathersName` varchar(255),
	`tin` varchar(50),
	`philsysId` varchar(50),
	`mobileNumber` varchar(20),
	`phoneNumber` varchar(20),
	`emailAddress` varchar(320),
	`homeBuilding` varchar(255),
	`homeStreet` varchar(255),
	`homeBarangay` varchar(255),
	`homeCity` varchar(255),
	`homeProvince` varchar(255),
	`homeRegion` varchar(255),
	`homeZipCode` varchar(10),
	`businessName` varchar(500),
	`businessNameOption2` varchar(500),
	`businessNameOption3` varchar(500),
	`businessType` varchar(255),
	`businessActivity` text,
	`territorialScope` enum('barangay','city','regional','national') DEFAULT 'city',
	`bizBuilding` varchar(255),
	`bizStreet` varchar(255),
	`bizBarangay` varchar(255),
	`bizCity` varchar(255) DEFAULT 'Manila',
	`bizProvince` varchar(255) DEFAULT 'Metro Manila',
	`bizRegion` varchar(255) DEFAULT 'NCR',
	`bizZipCode` varchar(10),
	`capitalization` int,
	`expectedAnnualSales` enum('micro','small','medium','large') DEFAULT 'micro',
	`numberOfEmployees` int DEFAULT 0,
	`preferTaxOption` enum('graduated','eight_percent') DEFAULT 'eight_percent',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `negosyante_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `negosyante_profiles_userId_unique` UNIQUE(`userId`)
);
