import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Community posts for the Negosyante Hub.
 * Reddit-style community board where vendors share tips, warn about fixers, and post LGU experiences.
 */
export const communityPosts = mysqlTable("community_posts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  authorName: varchar("authorName", { length: 255 }).notNull(),
  lguTag: varchar("lguTag", { length: 100 }).notNull().default("manila_city"),
  category: mysqlEnum("category", ["tip", "warning", "question", "experience"]).notNull().default("tip"),
  title: varchar("title", { length: 500 }).notNull(),
  content: text("content").notNull(),
  upvotes: int("upvotes").notNull().default(0),
  downvotes: int("downvotes").notNull().default(0),
  isFlagged: boolean("isFlagged").notNull().default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CommunityPost = typeof communityPosts.$inferSelect;
export type InsertCommunityPost = typeof communityPosts.$inferInsert;

/**
 * Votes tracking for community posts (one vote per user per post).
 */
export const postVotes = mysqlTable("post_votes", {
  id: int("id").autoincrement().primaryKey(),
  postId: int("postId").notNull(),
  userId: int("userId").notNull(),
  voteType: mysqlEnum("voteType", ["up", "down"]).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PostVote = typeof postVotes.$inferSelect;
export type InsertPostVote = typeof postVotes.$inferInsert;

/**
 * Saved roadmaps generated by the AI for each user.
 */
export const roadmaps = mysqlTable("roadmaps", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  lguId: varchar("lguId", { length: 100 }).notNull().default("manila_city"),
  businessType: varchar("businessType", { length: 255 }),
  district: varchar("district", { length: 255 }),
  totalEstimatedCostMin: int("totalEstimatedCostMin"),
  totalEstimatedCostMax: int("totalEstimatedCostMax"),
  completedSteps: json("completedSteps").$type<number[]>().default([]),
  checkedDocuments: json("checkedDocuments").$type<Record<string, string[]>>().default({}),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Roadmap = typeof roadmaps.$inferSelect;
export type InsertRoadmap = typeof roadmaps.$inferInsert;

/**
 * Feedback and reports for outdated info, incorrect data, etc.
 */
export const feedback = mysqlTable("feedback", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId"),
  feedbackType: mysqlEnum("feedbackType", ["outdated_info", "incorrect_data", "suggestion", "bug_report", "general"]).notNull(),
  stepNumber: int("stepNumber"),
  lguId: varchar("lguId", { length: 100 }).default("manila_city"),
  message: text("message").notNull(),
  status: mysqlEnum("status", ["pending", "reviewed", "resolved"]).default("pending").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Feedback = typeof feedback.$inferSelect;
export type InsertFeedback = typeof feedback.$inferInsert;
