// Plain-text fallback PDF for forms without an AcroForm template yet (DTI, BIR).
// Uses pdf-lib to produce a real, viewable PDF — not a base64 of plain text.
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function renderTextFallback(
  title: string,
  fields: Record<string, string>,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([612, 792]); // US Letter
  const margin = 54;
  let y = 792 - margin;

  const drawLine = (text: string, opts: { bold?: boolean; size?: number } = {}) => {
    const size = opts.size ?? 11;
    if (y < margin + size) {
      page = pdf.addPage([612, 792]);
      y = 792 - margin;
    }
    page.drawText(text, {
      x: margin,
      y,
      size,
      font: opts.bold ? fontBold : font,
      color: rgb(0.15, 0.15, 0.15),
    });
    y -= size + 6;
  };

  drawLine(title, { bold: true, size: 14 });
  drawLine(`Generated by NegosyoNav · ${new Date().toLocaleDateString("en-PH")}`, { size: 9 });
  y -= 8;

  for (const [key, value] of Object.entries(fields)) {
    const label = key.replace(/^(dti|bir|brgy)_/, "").replace(/_/g, " ").toUpperCase();
    drawLine(`${label}: ${value || "(blank)"}`);
  }

  y -= 12;
  drawLine("This is a pre-filled reference. Please transfer to the official form.", { size: 9 });
  drawLine("Official DTI form: bnrs.dti.gov.ph", { size: 9 });
  drawLine("Official BIR form: bir.gov.ph", { size: 9 });

  return pdf.save();
}
